# Generated by Django 5.1.4 on 2024-12-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('contenido', models.CharField(max_length=10000)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
